import './globals.css'

export const metadata = {
  title: 'To Do List',
  description: 'Generated by YUN',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        {children}
      </body>
    </html>
  )
}
