import './globals.css'

export const metadata = {
  title: 'To Do List',
  description: 'Generated by YUN',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div className='List-wrap'>
          <h2>To Do List</h2>
          {children}
        </div>
      </body>
    </html>
  )
}
